### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theodorosploumis** [drupaltools/drupaltools.github.io#2]
## Functionality
- [ ] Responsive tables
- [ ] Add sponsorship block
- [ ] Show results (count)
- [ ] Results - Sort By
- [ ] Results - Filter By
- [ ] Sticky table th
- [ ] Create Page for each project (?)

## Promote and make public
- [ ] Crate a logo  (?)
- [ ] My Blog
- [ ] D.O.
- [ ] Social accounts
- [ ] Issue on project owners
- [ ] local community post
- [ ]
